project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll
    - images/github.png
    - "assets/pdfs/PriceBeo Business Report.pdf"
    - "assets/pdfs/Research_Report_22420692.pdf"
    - "assets/pdfs/online_shoppers_ml_analysis_22420692.pdf"
    - "assets/pdfs/Data analytics group project.pdf"
    - "assets/pdfs/EcoEnergy-Corp-Global-Sustainable-Infrastructure ptp.pdf"
    - "assets/pdfs/Power Bi Group Project powerbi.pdf"
    - "assets/pdfs/Big Enterprise - Applegreen innovation - SB104.pdf"
    - "assets/pdfs/Semester 2 Final Assignment (25%) SB202.pdf"
    - "assets/pdfs/pricebeo-slides.pdf"
    - "assets/pdfs/superdry.pdf"
    - assets/ireland-counties.geojson

website:
  title: "Aleksander Lupa"
  favicon: images/flavicon.png
  navbar:
    logo: images/website.logo.png
    right:
      - href: projects/index.qmd
        text: Projects
      - href: future_goals.qmd
        text: Future Goals
      - href: achievements.qmd
        text: Achievements
      - href: about.qmd
        text: About
      - href: cv/Aleksander_Lupa_CV.pdf
        text: CV
        target: _blank
      - href: https://github.com/alekslupa
        icon: github
        target: _blank
        rel: noopener
  page-footer:
    left: "© 2026 Aleksander Lupa"
    right: "Built by <a href='https://quarto.org' target='_blank'>Quarto</a>"

format:
  html:
    theme:
      light: [cosmo, styles.scss]
      dark: [darkly, styles.scss]
    toc: true
    include-after-body: back-to-top.html



