project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "Aleksander Lupa"
  navbar:
    logo: assets/website.logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
  page-footer:
    left: "© 2026 Aleksander Lupa"
    right: "Built by <a href='https://quarto.org' target='_blank'>Quarto</a>"

format:
  html:
    theme:
      - cosmo
      - styles.scss
    toc: true



